title: FriishProduce
description: World's first WYSYWYG injector for Wii Virtual Console
author: "CatmanFan / Mr. Lechkar"

theme: minima

base_url: /
repository: CatmanFan/friishproduce-wiki

# Minima social links
github_username: CatmanFan

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
